// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TravelAgencyProtocol
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from TravelAgencyProtocol</summary>
public static partial class TravelAgencyProtocolReflection {

  #region Descriptor
  /// <summary>File descriptor for TravelAgencyProtocol</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static TravelAgencyProtocolReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChRUcmF2ZWxBZ2VuY3lQcm90b2NvbCI2CgRVc2VyEgoKAmlkGAEgASgDEhAK",
          "CHVzZXJuYW1lGAIgASgJEhAKCHBhc3N3b3JkGAMgASgJIoABCgRUcmlwEgoK",
          "AmlkGAEgASgDEhAKCGxhbmRtYXJrGAIgASgJEhwKFHRyYW5zcG9ydENvbXBh",
          "bnlOYW1lGAMgASgJEhUKDWRlcGFydHVyZVRpbWUYBCABKAkSDQoFcHJpY2UY",
          "BSABKAISFgoOYXZhaWxhYmxlU2VhdHMYBiABKAUihQEKC1Jlc2VydmF0aW9u",
          "EgoKAmlkGAEgASgDEhIKCmNsaWVudE5hbWUYAiABKAkSEwoLcGhvbmVOdW1i",
          "ZXIYAyABKAkSFwoPbnVtYmVyT2ZUaWNrZXRzGAQgASgFEhMKBHVzZXIYBSAB",
          "KAsyBS5Vc2VyEhMKBHRyaXAYBiABKAsyBS5UcmlwIqwCCgdSZXF1ZXN0EiIK",
          "BHR5cGUYASABKA4yFC5SZXF1ZXN0LlJlcXVlc3RUeXBlEhUKBHVzZXIYAiAB",
          "KAsyBS5Vc2VySAASFQoEdHJpcBgDIAEoCzIFLlRyaXBIABIjCgtyZXNlcnZh",
          "dGlvbhgEIAEoCzIMLlJlc2VydmF0aW9uSAASEAoIbGFuZG1hcmsYBSABKAkS",
          "EQoJc3RhcnRIb3VyGAYgASgFEg8KB2VuZEhvdXIYByABKAUiaQoLUmVxdWVz",
          "dFR5cGUSCwoHVW5rbm93bhAAEgkKBUxvZ2luEAESCgoGTG9nb3V0EAISDwoL",
          "R2V0QWxsVHJpcHMQAxIUChBHZXRTZWFyY2hlZFRyaXBzEAQSDwoLUmVzZXJ2",
          "ZVRyaXAQBUIJCgdwYXlsb2FkIv4BCghSZXNwb25zZRIkCgR0eXBlGAEgASgO",
          "MhYuUmVzcG9uc2UuUmVzcG9uc2VUeXBlEhkKDGVycm9yTWVzc2FnZRgCIAEo",
          "CUgAiAEBEhQKBXRyaXBzGAMgAygLMgUuVHJpcBIhCgtyZXNlcnZhdGlvbhgE",
          "IAEoCzIMLlJlc2VydmF0aW9uImcKDFJlc3BvbnNlVHlwZRILCgdVbmtub3du",
          "EAASBgoCT2sQARIJCgVFcnJvchACEhAKDFRyaXBSZXNlcnZlZBADEg8KC0dl",
          "dEFsbFRyaXBzEAQSFAoQR2V0U2VhcmNoZWRUcmlwcxAFQg8KDV9lcnJvck1l",
          "c3NhZ2VCPwomdHJhdmVsQWdlbmN5Lm5ldHdvcmsucHJvdG9idWZmcHJvdG9j",
          "b2xCFVRyYXZlbEFnZW5jeVByb3RvYnVmc2IGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::User), global::User.Parser, new[]{ "Id", "Username", "Password" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Trip), global::Trip.Parser, new[]{ "Id", "Landmark", "TransportCompanyName", "DepartureTime", "Price", "AvailableSeats" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Reservation), global::Reservation.Parser, new[]{ "Id", "ClientName", "PhoneNumber", "NumberOfTickets", "User", "Trip" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Request), global::Request.Parser, new[]{ "Type", "User", "Trip", "Reservation", "Landmark", "StartHour", "EndHour" }, new[]{ "Payload" }, new[]{ typeof(global::Request.Types.RequestType) }, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Response), global::Response.Parser, new[]{ "Type", "ErrorMessage", "Trips", "Reservation" }, new[]{ "ErrorMessage" }, new[]{ typeof(global::Response.Types.ResponseType) }, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class User : pb::IMessage<User>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<User> _parser = new pb::MessageParser<User>(() => new User());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<User> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::TravelAgencyProtocolReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public User() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public User(User other) : this() {
    id_ = other.id_;
    username_ = other.username_;
    password_ = other.password_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public User Clone() {
    return new User(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private long id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "username" field.</summary>
  public const int UsernameFieldNumber = 2;
  private string username_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Username {
    get { return username_; }
    set {
      username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "password" field.</summary>
  public const int PasswordFieldNumber = 3;
  private string password_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Password {
    get { return password_; }
    set {
      password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as User);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(User other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Username != other.Username) return false;
    if (Password != other.Password) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0L) hash ^= Id.GetHashCode();
    if (Username.Length != 0) hash ^= Username.GetHashCode();
    if (Password.Length != 0) hash ^= Password.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Username.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Username);
    }
    if (Password.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Password);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Username.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Username);
    }
    if (Password.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Password);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
    }
    if (Username.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
    }
    if (Password.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(User other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0L) {
      Id = other.Id;
    }
    if (other.Username.Length != 0) {
      Username = other.Username;
    }
    if (other.Password.Length != 0) {
      Password = other.Password;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 18: {
          Username = input.ReadString();
          break;
        }
        case 26: {
          Password = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 18: {
          Username = input.ReadString();
          break;
        }
        case 26: {
          Password = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class Trip : pb::IMessage<Trip>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Trip> _parser = new pb::MessageParser<Trip>(() => new Trip());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Trip> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::TravelAgencyProtocolReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Trip() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Trip(Trip other) : this() {
    id_ = other.id_;
    landmark_ = other.landmark_;
    transportCompanyName_ = other.transportCompanyName_;
    departureTime_ = other.departureTime_;
    price_ = other.price_;
    availableSeats_ = other.availableSeats_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Trip Clone() {
    return new Trip(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private long id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "landmark" field.</summary>
  public const int LandmarkFieldNumber = 2;
  private string landmark_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Landmark {
    get { return landmark_; }
    set {
      landmark_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "transportCompanyName" field.</summary>
  public const int TransportCompanyNameFieldNumber = 3;
  private string transportCompanyName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string TransportCompanyName {
    get { return transportCompanyName_; }
    set {
      transportCompanyName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "departureTime" field.</summary>
  public const int DepartureTimeFieldNumber = 4;
  private string departureTime_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string DepartureTime {
    get { return departureTime_; }
    set {
      departureTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "price" field.</summary>
  public const int PriceFieldNumber = 5;
  private float price_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Price {
    get { return price_; }
    set {
      price_ = value;
    }
  }

  /// <summary>Field number for the "availableSeats" field.</summary>
  public const int AvailableSeatsFieldNumber = 6;
  private int availableSeats_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int AvailableSeats {
    get { return availableSeats_; }
    set {
      availableSeats_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Trip);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Trip other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Landmark != other.Landmark) return false;
    if (TransportCompanyName != other.TransportCompanyName) return false;
    if (DepartureTime != other.DepartureTime) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Price, other.Price)) return false;
    if (AvailableSeats != other.AvailableSeats) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0L) hash ^= Id.GetHashCode();
    if (Landmark.Length != 0) hash ^= Landmark.GetHashCode();
    if (TransportCompanyName.Length != 0) hash ^= TransportCompanyName.GetHashCode();
    if (DepartureTime.Length != 0) hash ^= DepartureTime.GetHashCode();
    if (Price != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Price);
    if (AvailableSeats != 0) hash ^= AvailableSeats.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Landmark.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Landmark);
    }
    if (TransportCompanyName.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(TransportCompanyName);
    }
    if (DepartureTime.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(DepartureTime);
    }
    if (Price != 0F) {
      output.WriteRawTag(45);
      output.WriteFloat(Price);
    }
    if (AvailableSeats != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(AvailableSeats);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Landmark.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Landmark);
    }
    if (TransportCompanyName.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(TransportCompanyName);
    }
    if (DepartureTime.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(DepartureTime);
    }
    if (Price != 0F) {
      output.WriteRawTag(45);
      output.WriteFloat(Price);
    }
    if (AvailableSeats != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(AvailableSeats);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
    }
    if (Landmark.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Landmark);
    }
    if (TransportCompanyName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(TransportCompanyName);
    }
    if (DepartureTime.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(DepartureTime);
    }
    if (Price != 0F) {
      size += 1 + 4;
    }
    if (AvailableSeats != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(AvailableSeats);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Trip other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0L) {
      Id = other.Id;
    }
    if (other.Landmark.Length != 0) {
      Landmark = other.Landmark;
    }
    if (other.TransportCompanyName.Length != 0) {
      TransportCompanyName = other.TransportCompanyName;
    }
    if (other.DepartureTime.Length != 0) {
      DepartureTime = other.DepartureTime;
    }
    if (other.Price != 0F) {
      Price = other.Price;
    }
    if (other.AvailableSeats != 0) {
      AvailableSeats = other.AvailableSeats;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 18: {
          Landmark = input.ReadString();
          break;
        }
        case 26: {
          TransportCompanyName = input.ReadString();
          break;
        }
        case 34: {
          DepartureTime = input.ReadString();
          break;
        }
        case 45: {
          Price = input.ReadFloat();
          break;
        }
        case 48: {
          AvailableSeats = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 18: {
          Landmark = input.ReadString();
          break;
        }
        case 26: {
          TransportCompanyName = input.ReadString();
          break;
        }
        case 34: {
          DepartureTime = input.ReadString();
          break;
        }
        case 45: {
          Price = input.ReadFloat();
          break;
        }
        case 48: {
          AvailableSeats = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class Reservation : pb::IMessage<Reservation>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Reservation> _parser = new pb::MessageParser<Reservation>(() => new Reservation());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Reservation> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::TravelAgencyProtocolReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Reservation() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Reservation(Reservation other) : this() {
    id_ = other.id_;
    clientName_ = other.clientName_;
    phoneNumber_ = other.phoneNumber_;
    numberOfTickets_ = other.numberOfTickets_;
    user_ = other.user_ != null ? other.user_.Clone() : null;
    trip_ = other.trip_ != null ? other.trip_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Reservation Clone() {
    return new Reservation(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private long id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "clientName" field.</summary>
  public const int ClientNameFieldNumber = 2;
  private string clientName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ClientName {
    get { return clientName_; }
    set {
      clientName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "phoneNumber" field.</summary>
  public const int PhoneNumberFieldNumber = 3;
  private string phoneNumber_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string PhoneNumber {
    get { return phoneNumber_; }
    set {
      phoneNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "numberOfTickets" field.</summary>
  public const int NumberOfTicketsFieldNumber = 4;
  private int numberOfTickets_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int NumberOfTickets {
    get { return numberOfTickets_; }
    set {
      numberOfTickets_ = value;
    }
  }

  /// <summary>Field number for the "user" field.</summary>
  public const int UserFieldNumber = 5;
  private global::User user_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::User User {
    get { return user_; }
    set {
      user_ = value;
    }
  }

  /// <summary>Field number for the "trip" field.</summary>
  public const int TripFieldNumber = 6;
  private global::Trip trip_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Trip Trip {
    get { return trip_; }
    set {
      trip_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Reservation);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Reservation other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (ClientName != other.ClientName) return false;
    if (PhoneNumber != other.PhoneNumber) return false;
    if (NumberOfTickets != other.NumberOfTickets) return false;
    if (!object.Equals(User, other.User)) return false;
    if (!object.Equals(Trip, other.Trip)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0L) hash ^= Id.GetHashCode();
    if (ClientName.Length != 0) hash ^= ClientName.GetHashCode();
    if (PhoneNumber.Length != 0) hash ^= PhoneNumber.GetHashCode();
    if (NumberOfTickets != 0) hash ^= NumberOfTickets.GetHashCode();
    if (user_ != null) hash ^= User.GetHashCode();
    if (trip_ != null) hash ^= Trip.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (ClientName.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(ClientName);
    }
    if (PhoneNumber.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(PhoneNumber);
    }
    if (NumberOfTickets != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(NumberOfTickets);
    }
    if (user_ != null) {
      output.WriteRawTag(42);
      output.WriteMessage(User);
    }
    if (trip_ != null) {
      output.WriteRawTag(50);
      output.WriteMessage(Trip);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (ClientName.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(ClientName);
    }
    if (PhoneNumber.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(PhoneNumber);
    }
    if (NumberOfTickets != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(NumberOfTickets);
    }
    if (user_ != null) {
      output.WriteRawTag(42);
      output.WriteMessage(User);
    }
    if (trip_ != null) {
      output.WriteRawTag(50);
      output.WriteMessage(Trip);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
    }
    if (ClientName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientName);
    }
    if (PhoneNumber.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(PhoneNumber);
    }
    if (NumberOfTickets != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumberOfTickets);
    }
    if (user_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(User);
    }
    if (trip_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Trip);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Reservation other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0L) {
      Id = other.Id;
    }
    if (other.ClientName.Length != 0) {
      ClientName = other.ClientName;
    }
    if (other.PhoneNumber.Length != 0) {
      PhoneNumber = other.PhoneNumber;
    }
    if (other.NumberOfTickets != 0) {
      NumberOfTickets = other.NumberOfTickets;
    }
    if (other.user_ != null) {
      if (user_ == null) {
        User = new global::User();
      }
      User.MergeFrom(other.User);
    }
    if (other.trip_ != null) {
      if (trip_ == null) {
        Trip = new global::Trip();
      }
      Trip.MergeFrom(other.Trip);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 18: {
          ClientName = input.ReadString();
          break;
        }
        case 26: {
          PhoneNumber = input.ReadString();
          break;
        }
        case 32: {
          NumberOfTickets = input.ReadInt32();
          break;
        }
        case 42: {
          if (user_ == null) {
            User = new global::User();
          }
          input.ReadMessage(User);
          break;
        }
        case 50: {
          if (trip_ == null) {
            Trip = new global::Trip();
          }
          input.ReadMessage(Trip);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 18: {
          ClientName = input.ReadString();
          break;
        }
        case 26: {
          PhoneNumber = input.ReadString();
          break;
        }
        case 32: {
          NumberOfTickets = input.ReadInt32();
          break;
        }
        case 42: {
          if (user_ == null) {
            User = new global::User();
          }
          input.ReadMessage(User);
          break;
        }
        case 50: {
          if (trip_ == null) {
            Trip = new global::Trip();
          }
          input.ReadMessage(Trip);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class Request : pb::IMessage<Request>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Request> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::TravelAgencyProtocolReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Request() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Request(Request other) : this() {
    type_ = other.type_;
    landmark_ = other.landmark_;
    startHour_ = other.startHour_;
    endHour_ = other.endHour_;
    switch (other.PayloadCase) {
      case PayloadOneofCase.User:
        User = other.User.Clone();
        break;
      case PayloadOneofCase.Trip:
        Trip = other.Trip.Clone();
        break;
      case PayloadOneofCase.Reservation:
        Reservation = other.Reservation.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Request Clone() {
    return new Request(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private global::Request.Types.RequestType type_ = global::Request.Types.RequestType.Unknown;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Request.Types.RequestType Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "user" field.</summary>
  public const int UserFieldNumber = 2;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::User User {
    get { return payloadCase_ == PayloadOneofCase.User ? (global::User) payload_ : null; }
    set {
      payload_ = value;
      payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.User;
    }
  }

  /// <summary>Field number for the "trip" field.</summary>
  public const int TripFieldNumber = 3;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Trip Trip {
    get { return payloadCase_ == PayloadOneofCase.Trip ? (global::Trip) payload_ : null; }
    set {
      payload_ = value;
      payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Trip;
    }
  }

  /// <summary>Field number for the "reservation" field.</summary>
  public const int ReservationFieldNumber = 4;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Reservation Reservation {
    get { return payloadCase_ == PayloadOneofCase.Reservation ? (global::Reservation) payload_ : null; }
    set {
      payload_ = value;
      payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Reservation;
    }
  }

  /// <summary>Field number for the "landmark" field.</summary>
  public const int LandmarkFieldNumber = 5;
  private string landmark_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Landmark {
    get { return landmark_; }
    set {
      landmark_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "startHour" field.</summary>
  public const int StartHourFieldNumber = 6;
  private int startHour_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int StartHour {
    get { return startHour_; }
    set {
      startHour_ = value;
    }
  }

  /// <summary>Field number for the "endHour" field.</summary>
  public const int EndHourFieldNumber = 7;
  private int endHour_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int EndHour {
    get { return endHour_; }
    set {
      endHour_ = value;
    }
  }

  private object payload_;
  /// <summary>Enum of possible cases for the "payload" oneof.</summary>
  public enum PayloadOneofCase {
    None = 0,
    User = 2,
    Trip = 3,
    Reservation = 4,
  }
  private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PayloadOneofCase PayloadCase {
    get { return payloadCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearPayload() {
    payloadCase_ = PayloadOneofCase.None;
    payload_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Request);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Request other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (!object.Equals(User, other.User)) return false;
    if (!object.Equals(Trip, other.Trip)) return false;
    if (!object.Equals(Reservation, other.Reservation)) return false;
    if (Landmark != other.Landmark) return false;
    if (StartHour != other.StartHour) return false;
    if (EndHour != other.EndHour) return false;
    if (PayloadCase != other.PayloadCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != global::Request.Types.RequestType.Unknown) hash ^= Type.GetHashCode();
    if (payloadCase_ == PayloadOneofCase.User) hash ^= User.GetHashCode();
    if (payloadCase_ == PayloadOneofCase.Trip) hash ^= Trip.GetHashCode();
    if (payloadCase_ == PayloadOneofCase.Reservation) hash ^= Reservation.GetHashCode();
    if (Landmark.Length != 0) hash ^= Landmark.GetHashCode();
    if (StartHour != 0) hash ^= StartHour.GetHashCode();
    if (EndHour != 0) hash ^= EndHour.GetHashCode();
    hash ^= (int) payloadCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Type != global::Request.Types.RequestType.Unknown) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (payloadCase_ == PayloadOneofCase.User) {
      output.WriteRawTag(18);
      output.WriteMessage(User);
    }
    if (payloadCase_ == PayloadOneofCase.Trip) {
      output.WriteRawTag(26);
      output.WriteMessage(Trip);
    }
    if (payloadCase_ == PayloadOneofCase.Reservation) {
      output.WriteRawTag(34);
      output.WriteMessage(Reservation);
    }
    if (Landmark.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Landmark);
    }
    if (StartHour != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(StartHour);
    }
    if (EndHour != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(EndHour);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Type != global::Request.Types.RequestType.Unknown) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (payloadCase_ == PayloadOneofCase.User) {
      output.WriteRawTag(18);
      output.WriteMessage(User);
    }
    if (payloadCase_ == PayloadOneofCase.Trip) {
      output.WriteRawTag(26);
      output.WriteMessage(Trip);
    }
    if (payloadCase_ == PayloadOneofCase.Reservation) {
      output.WriteRawTag(34);
      output.WriteMessage(Reservation);
    }
    if (Landmark.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Landmark);
    }
    if (StartHour != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(StartHour);
    }
    if (EndHour != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(EndHour);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Type != global::Request.Types.RequestType.Unknown) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (payloadCase_ == PayloadOneofCase.User) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(User);
    }
    if (payloadCase_ == PayloadOneofCase.Trip) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Trip);
    }
    if (payloadCase_ == PayloadOneofCase.Reservation) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Reservation);
    }
    if (Landmark.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Landmark);
    }
    if (StartHour != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(StartHour);
    }
    if (EndHour != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(EndHour);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Request other) {
    if (other == null) {
      return;
    }
    if (other.Type != global::Request.Types.RequestType.Unknown) {
      Type = other.Type;
    }
    if (other.Landmark.Length != 0) {
      Landmark = other.Landmark;
    }
    if (other.StartHour != 0) {
      StartHour = other.StartHour;
    }
    if (other.EndHour != 0) {
      EndHour = other.EndHour;
    }
    switch (other.PayloadCase) {
      case PayloadOneofCase.User:
        if (User == null) {
          User = new global::User();
        }
        User.MergeFrom(other.User);
        break;
      case PayloadOneofCase.Trip:
        if (Trip == null) {
          Trip = new global::Trip();
        }
        Trip.MergeFrom(other.Trip);
        break;
      case PayloadOneofCase.Reservation:
        if (Reservation == null) {
          Reservation = new global::Reservation();
        }
        Reservation.MergeFrom(other.Reservation);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = (global::Request.Types.RequestType) input.ReadEnum();
          break;
        }
        case 18: {
          global::User subBuilder = new global::User();
          if (payloadCase_ == PayloadOneofCase.User) {
            subBuilder.MergeFrom(User);
          }
          input.ReadMessage(subBuilder);
          User = subBuilder;
          break;
        }
        case 26: {
          global::Trip subBuilder = new global::Trip();
          if (payloadCase_ == PayloadOneofCase.Trip) {
            subBuilder.MergeFrom(Trip);
          }
          input.ReadMessage(subBuilder);
          Trip = subBuilder;
          break;
        }
        case 34: {
          global::Reservation subBuilder = new global::Reservation();
          if (payloadCase_ == PayloadOneofCase.Reservation) {
            subBuilder.MergeFrom(Reservation);
          }
          input.ReadMessage(subBuilder);
          Reservation = subBuilder;
          break;
        }
        case 42: {
          Landmark = input.ReadString();
          break;
        }
        case 48: {
          StartHour = input.ReadInt32();
          break;
        }
        case 56: {
          EndHour = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Type = (global::Request.Types.RequestType) input.ReadEnum();
          break;
        }
        case 18: {
          global::User subBuilder = new global::User();
          if (payloadCase_ == PayloadOneofCase.User) {
            subBuilder.MergeFrom(User);
          }
          input.ReadMessage(subBuilder);
          User = subBuilder;
          break;
        }
        case 26: {
          global::Trip subBuilder = new global::Trip();
          if (payloadCase_ == PayloadOneofCase.Trip) {
            subBuilder.MergeFrom(Trip);
          }
          input.ReadMessage(subBuilder);
          Trip = subBuilder;
          break;
        }
        case 34: {
          global::Reservation subBuilder = new global::Reservation();
          if (payloadCase_ == PayloadOneofCase.Reservation) {
            subBuilder.MergeFrom(Reservation);
          }
          input.ReadMessage(subBuilder);
          Reservation = subBuilder;
          break;
        }
        case 42: {
          Landmark = input.ReadString();
          break;
        }
        case 48: {
          StartHour = input.ReadInt32();
          break;
        }
        case 56: {
          EndHour = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the Request message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public enum RequestType {
      [pbr::OriginalName("Unknown")] Unknown = 0,
      [pbr::OriginalName("Login")] Login = 1,
      [pbr::OriginalName("Logout")] Logout = 2,
      [pbr::OriginalName("GetAllTrips")] GetAllTrips = 3,
      [pbr::OriginalName("GetSearchedTrips")] GetSearchedTrips = 4,
      [pbr::OriginalName("ReserveTrip")] ReserveTrip = 5,
    }

  }
  #endregion

}

public sealed partial class Response : pb::IMessage<Response>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Response> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::TravelAgencyProtocolReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Response() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Response(Response other) : this() {
    type_ = other.type_;
    errorMessage_ = other.errorMessage_;
    trips_ = other.trips_.Clone();
    reservation_ = other.reservation_ != null ? other.reservation_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Response Clone() {
    return new Response(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private global::Response.Types.ResponseType type_ = global::Response.Types.ResponseType.Unknown;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Response.Types.ResponseType Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "errorMessage" field.</summary>
  public const int ErrorMessageFieldNumber = 2;
  private string errorMessage_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ErrorMessage {
    get { return errorMessage_ ?? ""; }
    set {
      errorMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "errorMessage" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasErrorMessage {
    get { return errorMessage_ != null; }
  }
  /// <summary>Clears the value of the "errorMessage" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearErrorMessage() {
    errorMessage_ = null;
  }

  /// <summary>Field number for the "trips" field.</summary>
  public const int TripsFieldNumber = 3;
  private static readonly pb::FieldCodec<global::Trip> _repeated_trips_codec
      = pb::FieldCodec.ForMessage(26, global::Trip.Parser);
  private readonly pbc::RepeatedField<global::Trip> trips_ = new pbc::RepeatedField<global::Trip>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::Trip> Trips {
    get { return trips_; }
  }

  /// <summary>Field number for the "reservation" field.</summary>
  public const int ReservationFieldNumber = 4;
  private global::Reservation reservation_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Reservation Reservation {
    get { return reservation_; }
    set {
      reservation_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Response);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Response other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (ErrorMessage != other.ErrorMessage) return false;
    if(!trips_.Equals(other.trips_)) return false;
    if (!object.Equals(Reservation, other.Reservation)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != global::Response.Types.ResponseType.Unknown) hash ^= Type.GetHashCode();
    if (HasErrorMessage) hash ^= ErrorMessage.GetHashCode();
    hash ^= trips_.GetHashCode();
    if (reservation_ != null) hash ^= Reservation.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Type != global::Response.Types.ResponseType.Unknown) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (HasErrorMessage) {
      output.WriteRawTag(18);
      output.WriteString(ErrorMessage);
    }
    trips_.WriteTo(output, _repeated_trips_codec);
    if (reservation_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Reservation);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Type != global::Response.Types.ResponseType.Unknown) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (HasErrorMessage) {
      output.WriteRawTag(18);
      output.WriteString(ErrorMessage);
    }
    trips_.WriteTo(ref output, _repeated_trips_codec);
    if (reservation_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Reservation);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Type != global::Response.Types.ResponseType.Unknown) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (HasErrorMessage) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorMessage);
    }
    size += trips_.CalculateSize(_repeated_trips_codec);
    if (reservation_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Reservation);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Response other) {
    if (other == null) {
      return;
    }
    if (other.Type != global::Response.Types.ResponseType.Unknown) {
      Type = other.Type;
    }
    if (other.HasErrorMessage) {
      ErrorMessage = other.ErrorMessage;
    }
    trips_.Add(other.trips_);
    if (other.reservation_ != null) {
      if (reservation_ == null) {
        Reservation = new global::Reservation();
      }
      Reservation.MergeFrom(other.Reservation);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = (global::Response.Types.ResponseType) input.ReadEnum();
          break;
        }
        case 18: {
          ErrorMessage = input.ReadString();
          break;
        }
        case 26: {
          trips_.AddEntriesFrom(input, _repeated_trips_codec);
          break;
        }
        case 34: {
          if (reservation_ == null) {
            Reservation = new global::Reservation();
          }
          input.ReadMessage(Reservation);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Type = (global::Response.Types.ResponseType) input.ReadEnum();
          break;
        }
        case 18: {
          ErrorMessage = input.ReadString();
          break;
        }
        case 26: {
          trips_.AddEntriesFrom(ref input, _repeated_trips_codec);
          break;
        }
        case 34: {
          if (reservation_ == null) {
            Reservation = new global::Reservation();
          }
          input.ReadMessage(Reservation);
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the Response message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public enum ResponseType {
      [pbr::OriginalName("Unknown")] Unknown = 0,
      [pbr::OriginalName("Ok")] Ok = 1,
      [pbr::OriginalName("Error")] Error = 2,
      [pbr::OriginalName("TripReserved")] TripReserved = 3,
      [pbr::OriginalName("GetAllTrips")] GetAllTrips = 4,
      [pbr::OriginalName("GetSearchedTrips")] GetSearchedTrips = 5,
    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
